export const DESTINATIONS = [
  {
    slug: "ocean",
    name: "Ocean",
    emoji: "🌊",
    tagline: "Let the tide carry some of it for you",
    storyTitle: "Chapter I · The Tide Gate",
    storyHook: "The sea is the first place the island sends you when your thoughts are too heavy to carry inland.",
    color: "#3a78a1",
    bgGradient: "linear-gradient(180deg, #061724 0%, #0d3146 26%, #15607e 58%, #72b6cb 82%, #d8edf4 100%)",
    particleType: "bubbles",
    voiceInstructions:
      "Use a hushed, fluid voice with soft breaths between sentences, like someone speaking near the shoreline at dusk.",
    videoUrl: "",
    ambientAudioUrl: "",
    isGallery: false,
    prompts: [
      {
        text: "You are standing at the edge of a quiet ocean.",
        voiceoverUrl: "",
      },
      { text: "The water keeps arriving, and it keeps letting go.", voiceoverUrl: "" },
      { text: "You do not have to hold everything at once here.", voiceoverUrl: "" },
      { text: "Let one thought drift out with the tide.", voiceoverUrl: "" },
      { text: "Let the next wave bring back only what you still need.", voiceoverUrl: "" },
      { text: "Stay as long as it helps.", voiceoverUrl: "" },
    ],
    voices: [],
    themeMedia: {
      homesickness: {
        introLine: "The tide gate opens when longing feels bigger than language.",
        voiceInstructions:
          "Sound especially tender and comforting here, with a slower pace and gentle emotional warmth.",
        prompts: [
          { text: "Homesickness can feel like being pulled by a current in two directions.", voiceoverUrl: "" },
          { text: "One part of you is here. Another part still reaches for home.", voiceoverUrl: "" },
          { text: "Imagine the tide touching both places at once, where you are and what you miss.", voiceoverUrl: "" },
          { text: "Nothing is wrong with you for longing.", voiceoverUrl: "" },
          { text: "Breathe in. Let the ocean hold what feels too heavy to name.", voiceoverUrl: "" },
        ],
      },
    },
  },
  {
    slug: "sky",
    name: "Sky",
    emoji: "☁️",
    tagline: "Fly like a bird",
    storyTitle: "Chapter II · The High Passage",
    storyHook: "When the ground feels too close, the island lifts you upward to see your life from a gentler distance.",
    color: "#5b7fa6",
    bgGradient: "linear-gradient(180deg, #1a2a4a 0%, #3a5a8a 30%, #7aaad4 60%, #c4dff0 85%, #f0e8d8 100%)",
    particleType: "clouds",
    voiceInstructions:
      "Use a light, airy tone with a little lift in the cadence, as if the words have space to drift.",
    videoUrl: "",
    ambientAudioUrl: "",
    isGallery: false,
    prompts: [
      { text: "Let's imagine you are a bird.", voiceoverUrl: "" },
      { text: "You are about to take flight.", voiceoverUrl: "" },
      { text: "Feel the wind beneath your wings as you lift off the ground.", voiceoverUrl: "" },
      { text: "Below you, everything gets smaller. The worries, the deadlines, the noise.", voiceoverUrl: "" },
      { text: "Where would you go if you could fly anywhere?", voiceoverUrl: "" },
      { text: "There's no destination. Just the feeling of being free.", voiceoverUrl: "" },
    ],
    voices: [],
    themeMedia: {
      homesickness: {
        introLine: "Some aches can only be understood once you rise above them.",
        videoUrl: "https://pub-11735088edf941b39e769dc13719a0a1.r2.dev/44123c8a-f098-4cbb-89b8-9d17a6540300.MP4",
      },
    },
  },
  {
    slug: "forest",
    name: "Forest",
    emoji: "🌲",
    tagline: "Find cover beneath something steady",
    storyTitle: "Chapter III · The Rooted Hollow",
    storyHook: "The forest waits deeper in the island, where quiet things help you remember what still holds.",
    color: "#4b6a47",
    bgGradient: "linear-gradient(180deg, #07140d 0%, #102719 28%, #274a31 58%, #55795a 82%, #c8d8bb 100%)",
    particleType: "none",
    voiceInstructions:
      "Use a grounded, steady, low-pressure voice that feels sheltered, patient, and calm.",
    videoUrl: "",
    ambientAudioUrl: "",
    isGallery: false,
    prompts: [
      { text: "You step into a forest where the air is cooler and slower.", voiceoverUrl: "" },
      { text: "The trees do not rush. They simply keep standing.", voiceoverUrl: "" },
      { text: "Notice the ground under you, solid and patient.", voiceoverUrl: "" },
      { text: "You are allowed to be quiet here.", voiceoverUrl: "" },
      { text: "You are allowed to take up space here too.", voiceoverUrl: "" },
      { text: "Rest for a moment beneath what is rooted.", voiceoverUrl: "" },
    ],
    voices: [],
    themeMedia: {
      homesickness: {
        introLine: "The hollow answers homesickness by teaching your body where shelter can still be found.",
        prompts: [
          { text: "Missing home can make everything feel less familiar than it should.", voiceoverUrl: "" },
          { text: "Let this forest become your borrowed shelter for now.", voiceoverUrl: "" },
          { text: "Picture each tree holding one memory that still belongs to you.", voiceoverUrl: "" },
          { text: "Home is not gone. It is part of what you carry.", voiceoverUrl: "" },
          { text: "Stand still long enough to feel that truth land.", voiceoverUrl: "" },
        ],
      },
    },
  },
  {
    slug: "gallery",
    name: "Gallery",
    emoji: "🖼️",
    tagline: "Words from those who've been there",
    storyTitle: "The Lantern Archive",
    storyHook: "Beyond the paths sits a room of voices left behind by travelers who made it through their own weather.",
    color: "#8a6b5e",
    bgGradient: "linear-gradient(135deg, #2a1f1a 0%, #4a3528 30%, #8a6b5e 60%, #c4a892 100%)",
    particleType: "none",
    videoUrl: "",
    ambientAudioUrl: "",
    isGallery: true,
    prompts: [],
    voices: [
      { text: "The loneliness hit me hardest in month two. But it passed. I promise it passes.", attribution: "Class of 2027", videoUrl: "" },
      { text: "I thought everyone had it figured out except me. Turns out, nobody did.", attribution: "Class of 2026", videoUrl: "" },
      { text: "Moving cities every semester felt impossible at first. Now it's my favorite part.", attribution: "Class of 2025", videoUrl: "" },
      { text: "I didn't ask for help until I was drowning. You don't have to wait that long.", attribution: "Class of 2027", videoUrl: "" },
      { text: "The hardest thing was letting go of who I was before. The best thing was finding who I became.", attribution: "Class of 2026", videoUrl: "" },
      { text: "Some days I just sat in a café alone and cried. And that was okay.", attribution: "Class of 2028", videoUrl: "" },
      { text: "Your path doesn't have to look like anyone else's. That's the whole point of being here.", attribution: "Class of 2025", videoUrl: "" },
      { text: "Berlin was lonely. Buenos Aires healed me. San Francisco challenged me. Every city taught me something.", attribution: "Class of 2026", videoUrl: "" },
    ],
    themeMedia: {},
  },
];

export const THEMES = [
  {
    slug: "homesickness",
    name: "Homesickness",
    emoji: "🏡",
    tagline: "Feel held while missing home",
    description: "A gentler space for the ache of missing what is familiar.",
    storyPrompt: "Tonight's quest asks you to cross the island while carrying the shape of home.",
    ambientAudioUrl: "https://cdn.pixabay.com/download/audio/2022/10/24/audio_946efc1b85.mp3?filename=ambient-meditation-118429.mp3",
  },
  {
    slug: "gallery",
    name: "Gallery",
    emoji: "🖼️",
    tagline: "Advice from other people",
    description: "Words from people who have already been through this kind of season.",
    storyPrompt: "This is where old travelers leave lanterns for the ones who arrive after them.",
    ambientAudioUrl: "",
    ambientLoopSegment: {
      mediaUrl: "https://pub-11735088edf941b39e769dc13719a0a1.r2.dev/44123c8a-f098-4cbb-89b8-9d17a6540300.MP4",
      startTime: 42,
      endTime: 114,
    },
  },
];
