export const DESTINATIONS = [
  {
    slug: "ocean",
    name: "Ocean",
    emoji: "🌊",
    tagline: "Let the tide carry some of it for you",
    storyTitle: "Chapter I · The Tide Gate",
    storyHook: "The sea is the first place the island sends you when your thoughts are too heavy to carry inland.",
    color: "#3a78a1",
    bgGradient: "linear-gradient(180deg, #061724 0%, #0d3146 26%, #15607e 58%, #72b6cb 82%, #d8edf4 100%)",
    particleType: "bubbles",
    voiceInstructions:
      "Use a hushed, fluid voice with soft breaths between sentences, like someone speaking near the shoreline at dusk.",
    videoUrl: "",
    ambientAudioUrl: "",
    isGallery: false,
    prompts: [
      {
        text: "You are standing at the edge of a quiet ocean.",
        voiceoverUrl: "",
      },
      { text: "The water keeps arriving, and it keeps letting go.", voiceoverUrl: "" },
      { text: "You do not have to hold everything at once here.", voiceoverUrl: "" },
      { text: "Let one thought drift out with the tide.", voiceoverUrl: "" },
      { text: "Let the next wave bring back only what you still need.", voiceoverUrl: "" },
      { text: "Stay as long as it helps.", voiceoverUrl: "" },
    ],
    voices: [],
    themeMedia: {
      homesickness: {
        introLine: "The tide gate opens when longing feels bigger than language.",
        voiceInstructions:
          "Sound especially tender and comforting here, with a slower pace and gentle emotional warmth.",
        prompts: [
          { text: "Homesickness can feel like being pulled by a current in two directions.", voiceoverUrl: "" },
          { text: "One part of you is here. Another part still reaches for home.", voiceoverUrl: "" },
          { text: "Imagine the tide touching both places at once, where you are and what you miss.", voiceoverUrl: "" },
          { text: "Nothing is wrong with you for longing.", voiceoverUrl: "" },
          { text: "Breathe in. Let the ocean hold what feels too heavy to name.", voiceoverUrl: "" },
        ],
      },
      stress: {
        introLine: "The tide gate opens when everything feels like too much to carry at once.",
        voiceInstructions:
          "Sound calming and steady here, like someone helping a person slow down near moving water.",
        prompts: [
          { text: "Stress can feel like a wave that keeps arriving before you have caught your breath.", voiceoverUrl: "" },
          { text: "Stand at the shoreline and let each thought come in one at a time.", voiceoverUrl: "" },
          { text: "You do not have to solve the whole sea tonight.", voiceoverUrl: "" },
          { text: "Choose one worry and let the tide pull it a little farther from your body.", voiceoverUrl: "" },
          { text: "Stay with the rhythm until your breath remembers a slower pace.", voiceoverUrl: "" },
        ],
      },
      "peer-pressure": {
        introLine: "The tide gate opens when other people's expectations are louder than your own voice.",
        voiceInstructions:
          "Sound reassuring and clear here, with a gentle confidence that helps the listener return to themselves.",
        prompts: [
          { text: "Peer pressure can sound like waves insisting you must move with everyone else.", voiceoverUrl: "" },
          { text: "But the shoreline keeps its own shape even when the water pushes against it.", voiceoverUrl: "" },
          { text: "Notice what is yours beneath the noise, the value, the boundary, the quiet no.", voiceoverUrl: "" },
          { text: "You are allowed to step back from what does not feel right in your chest.", voiceoverUrl: "" },
          { text: "Let the tide return you to your own edge.", voiceoverUrl: "" },
        ],
      },
    },
  },
  {
    slug: "sky",
    name: "Sky",
    emoji: "☁️",
    tagline: "Fly like a bird",
    storyTitle: "Chapter II · The High Passage",
    storyHook: "When the ground feels too close, the island lifts you upward to see your life from a gentler distance.",
    color: "#5b7fa6",
    bgGradient: "linear-gradient(180deg, #1a2a4a 0%, #3a5a8a 30%, #7aaad4 60%, #c4dff0 85%, #f0e8d8 100%)",
    particleType: "clouds",
    voiceInstructions:
      "Use a light, airy tone with a little lift in the cadence, as if the words have space to drift.",
    videoUrl: "",
    ambientAudioUrl: "",
    isGallery: false,
    prompts: [
      { text: "Let's imagine you are a bird.", voiceoverUrl: "" },
      { text: "You are about to take flight.", voiceoverUrl: "" },
      { text: "Feel the wind beneath your wings as you lift off the ground.", voiceoverUrl: "" },
      { text: "Below you, everything gets smaller. The worries, the deadlines, the noise.", voiceoverUrl: "" },
      { text: "Where would you go if you could fly anywhere?", voiceoverUrl: "" },
      { text: "There's no destination. Just the feeling of being free.", voiceoverUrl: "" },
    ],
    voices: [],
    themeMedia: {
      homesickness: {
        introLine: "Some aches can only be understood once you rise above them.",
        videoUrl: "https://pub-11735088edf941b39e769dc13719a0a1.r2.dev/44123c8a-f098-4cbb-89b8-9d17a6540300.MP4",
      },
      stress: {
        introLine: "The high passage opens when your mind is moving faster than your body can follow.",
        prompts: [
          { text: "Stress can pin you to the ground until everything feels urgent and close.", voiceoverUrl: "" },
          { text: "Now imagine lifting above it, not to escape, but to see more clearly.", voiceoverUrl: "" },
          { text: "From here, not every task deserves the same weight.", voiceoverUrl: "" },
          { text: "Let the highest pressure shrink until it becomes only one part of a much bigger sky.", voiceoverUrl: "" },
          { text: "You are allowed to come back down slower than you climbed up.", voiceoverUrl: "" },
        ],
      },
      "peer-pressure": {
        introLine: "The high passage opens when it feels like everyone else is choosing your direction for you.",
        prompts: [
          { text: "Peer pressure can make it feel dangerous to drift away from the flock.", voiceoverUrl: "" },
          { text: "But from high above, you can see there is more than one current to follow.", voiceoverUrl: "" },
          { text: "You do not have to fly where the loudest voices are pointing.", voiceoverUrl: "" },
          { text: "Choose the path that leaves space inside your chest, not just approval around you.", voiceoverUrl: "" },
          { text: "The sky is wide enough for your own direction.", voiceoverUrl: "" },
        ],
      },
    },
  },
  {
    slug: "forest",
    name: "Forest",
    emoji: "🌲",
    tagline: "Find cover beneath something steady",
    storyTitle: "Chapter III · The Rooted Hollow",
    storyHook: "The forest waits deeper in the island, where quiet things help you remember what still holds.",
    color: "#4b6a47",
    bgGradient: "linear-gradient(180deg, #07140d 0%, #102719 28%, #274a31 58%, #55795a 82%, #c8d8bb 100%)",
    particleType: "none",
    voiceInstructions:
      "Use a grounded, steady, low-pressure voice that feels sheltered, patient, and calm.",
    videoUrl: "",
    ambientAudioUrl: "",
    isGallery: false,
    prompts: [
      { text: "You step into a forest where the air is cooler and slower.", voiceoverUrl: "" },
      { text: "The trees do not rush. They simply keep standing.", voiceoverUrl: "" },
      { text: "Notice the ground under you, solid and patient.", voiceoverUrl: "" },
      { text: "You are allowed to be quiet here.", voiceoverUrl: "" },
      { text: "You are allowed to take up space here too.", voiceoverUrl: "" },
      { text: "Rest for a moment beneath what is rooted.", voiceoverUrl: "" },
    ],
    voices: [],
    themeMedia: {
      homesickness: {
        introLine: "The hollow answers homesickness by teaching your body where shelter can still be found.",
        prompts: [
          { text: "Missing home can make everything feel less familiar than it should.", voiceoverUrl: "" },
          { text: "Let this forest become your borrowed shelter for now.", voiceoverUrl: "" },
          { text: "Picture each tree holding one memory that still belongs to you.", voiceoverUrl: "" },
          { text: "Home is not gone. It is part of what you carry.", voiceoverUrl: "" },
          { text: "Stand still long enough to feel that truth land.", voiceoverUrl: "" },
        ],
      },
      stress: {
        introLine: "The rooted hollow opens when your nerves need something steadier than momentum.",
        prompts: [
          { text: "Stress can scatter your attention until you no longer feel where your own body ends.", voiceoverUrl: "" },
          { text: "Step deeper into the forest and feel the ground waiting for you without urgency.", voiceoverUrl: "" },
          { text: "The trees do not rush to prove themselves. They simply keep standing.", voiceoverUrl: "" },
          { text: "Let your shoulders lower by one small degree. Then another.", voiceoverUrl: "" },
          { text: "Stay long enough for steadiness to sound familiar again.", voiceoverUrl: "" },
        ],
      },
      "peer-pressure": {
        introLine: "The rooted hollow opens when outside voices are trying to shape you too quickly.",
        prompts: [
          { text: "Peer pressure can feel like being bent in a direction that is not your own.", voiceoverUrl: "" },
          { text: "But roots know how to hold their line underground where no one else can see.", voiceoverUrl: "" },
          { text: "You do not need to become louder to stay true to yourself.", voiceoverUrl: "" },
          { text: "Picture the trees around you guarding the space where your own choices begin.", voiceoverUrl: "" },
          { text: "What is grounded in you does not need permission to remain.", voiceoverUrl: "" },
        ],
      },
    },
  },
  {
    slug: "space",
    name: "Space",
    emoji: "🪐",
    tagline: "Float far enough to hear yourself again",
    storyTitle: "Chapter IV · The Quiet Orbit",
    storyHook: "When everything feels too loud and too close, the island opens a dark sky where distance becomes gentleness.",
    color: "#5b5f9e",
    bgGradient: "linear-gradient(180deg, #050816 0%, #111836 28%, #1f2854 58%, #4e5e95 82%, #d6defa 100%)",
    particleType: "stars",
    voiceInstructions:
      "Use a slow, spacious, weightless voice, like someone guiding you through stillness beneath a night sky.",
    videoUrl: "",
    ambientAudioUrl: "",
    isGallery: false,
    prompts: [
      { text: "You drift into a quiet stretch of space where everything finally grows wide enough to breathe.", voiceoverUrl: "" },
      { text: "The noise below you softens into distance.", voiceoverUrl: "" },
      { text: "There is no need to rush in a place that measures itself in stars.", voiceoverUrl: "" },
      { text: "Let one tight thought loosen and float away from your chest.", voiceoverUrl: "" },
      { text: "What remains is the part of you that still knows how to be still.", voiceoverUrl: "" },
      { text: "Stay in orbit until your breath feels like your own again.", voiceoverUrl: "" },
    ],
    voices: [],
    themeMedia: {
      homesickness: {
        introLine: "The quiet orbit opens when longing needs distance instead of pressure.",
        voiceInstructions:
          "Sound especially reassuring and spacious here, with long pauses and a softly anchoring tone.",
        prompts: [
          { text: "Homesickness can make every room feel smaller than it really is.", voiceoverUrl: "" },
          { text: "Imagine rising above that ache until it becomes a constellation instead of a weight.", voiceoverUrl: "" },
          { text: "You are allowed to miss what held you and still keep moving forward.", voiceoverUrl: "" },
          { text: "Out here, your longing is not a flaw. It is proof that you have loved something deeply.", voiceoverUrl: "" },
          { text: "Let the stars hold the parts that feel too far away tonight.", voiceoverUrl: "" },
        ],
      },
      stress: {
        introLine: "The quiet orbit opens when your thoughts are spinning too fast to rest.",
        prompts: [
          { text: "Stress can trap you in a tight orbit where the same worries keep circling.", voiceoverUrl: "" },
          { text: "Now imagine the space around you widening until there is room between every thought.", voiceoverUrl: "" },
          { text: "You do not have to chase each one as it passes.", voiceoverUrl: "" },
          { text: "Let the pressure lose gravity little by little.", voiceoverUrl: "" },
          { text: "Stay in the stillness until your mind stops bracing for impact.", voiceoverUrl: "" },
        ],
      },
      "peer-pressure": {
        introLine: "The quiet orbit opens when other people's expectations feel impossible to escape.",
        prompts: [
          { text: "Peer pressure can make it feel like every voice is pulling you into its own gravity.", voiceoverUrl: "" },
          { text: "But not every force deserves to keep you in orbit.", voiceoverUrl: "" },
          { text: "Out here, you can tell the difference between influence and truth.", voiceoverUrl: "" },
          { text: "Picture yourself drifting just far enough to hear your own answer more clearly than theirs.", voiceoverUrl: "" },
          { text: "You are allowed to choose a path that belongs only to you.", voiceoverUrl: "" },
        ],
      },
    },
  },
  {
    slug: "gallery",
    name: "Gallery",
    emoji: "🖼️",
    tagline: "Words from those who've been there",
    storyTitle: "The Lantern Archive",
    storyHook: "Beyond the paths sits a room of voices left behind by travelers who made it through their own weather.",
    color: "#8a6b5e",
    bgGradient: "linear-gradient(135deg, #2a1f1a 0%, #4a3528 30%, #8a6b5e 60%, #c4a892 100%)",
    particleType: "none",
    videoUrl: "",
    ambientAudioUrl: "",
    isGallery: true,
    prompts: [],
    voices: [
      { text: "The loneliness hit me hardest in month two. But it passed. I promise it passes.", attribution: "Class of 2027", videoUrl: "" },
      { text: "I thought everyone had it figured out except me. Turns out, nobody did.", attribution: "Class of 2026", videoUrl: "" },
      { text: "Moving cities every semester felt impossible at first. Now it's my favorite part.", attribution: "Class of 2025", videoUrl: "" },
      { text: "I didn't ask for help until I was drowning. You don't have to wait that long.", attribution: "Class of 2027", videoUrl: "" },
      { text: "The hardest thing was letting go of who I was before. The best thing was finding who I became.", attribution: "Class of 2026", videoUrl: "" },
      { text: "Some days I just sat in a café alone and cried. And that was okay.", attribution: "Class of 2028", videoUrl: "" },
      { text: "Your path doesn't have to look like anyone else's. That's the whole point of being here.", attribution: "Class of 2025", videoUrl: "" },
      { text: "Berlin was lonely. Buenos Aires healed me. San Francisco challenged me. Every city taught me something.", attribution: "Class of 2026", videoUrl: "" },
    ],
    themeMedia: {},
  },
];

export const THEMES = [
  {
    slug: "homesickness",
    name: "Homesickness",
    emoji: "🏡",
    tagline: "Feel held while missing home",
    description: "A gentler space for the ache of missing what is familiar.",
    storyPrompt: "Tonight's quest asks you to cross the island while carrying the shape of home.",
    ambientAudioUrl: "https://cdn.pixabay.com/download/audio/2022/10/24/audio_946efc1b85.mp3?filename=ambient-meditation-118429.mp3",
  },
  {
    slug: "stress",
    name: "Stress",
    emoji: "⏳",
    tagline: "Slow the pressure down",
    description: "A steadier space for the weight of deadlines, urgency, and too much at once.",
    storyPrompt: "Tonight's quest asks you to loosen the knot of pressure without needing to solve everything at once.",
    ambientAudioUrl: "https://cdn.pixabay.com/download/audio/2022/10/24/audio_946efc1b85.mp3?filename=ambient-meditation-118429.mp3",
  },
  {
    slug: "peer-pressure",
    name: "Peer Pressure",
    emoji: "🧭",
    tagline: "Return to your own direction",
    description: "A clearer space for outside expectations, comparison, and the pressure to fit.",
    storyPrompt: "Tonight's quest asks you to hear your own inner compass more clearly than the crowd around you.",
    ambientAudioUrl: "https://cdn.pixabay.com/download/audio/2022/10/24/audio_946efc1b85.mp3?filename=ambient-meditation-118429.mp3",
  },
  {
    slug: "gallery",
    name: "Gallery",
    emoji: "🖼️",
    tagline: "Advice from other people",
    description: "Words from people who have already been through this kind of season.",
    storyPrompt: "This is where old travelers leave lanterns for the ones who arrive after them.",
    ambientAudioUrl: "",
    ambientLoopSegment: {
      mediaUrl: "https://pub-11735088edf941b39e769dc13719a0a1.r2.dev/44123c8a-f098-4cbb-89b8-9d17a6540300.MP4",
      startTime: 42,
      endTime: 114,
    },
  },
];
